ds1:
  type: com.zaxxer.hikari.HikariDataSource
  jdbcUrl: jdbc:mysql://127.0.0.1:3306/employees?rewriteBatchedStatements=true
  driverClassName: com.mysql.cj.jdbc.Driver
  username: root
  password: root
ds2:
  type: com.zaxxer.hikari.HikariDataSource
  jdbcUrl: jdbc:mysql://127.0.0.1:3306/employees?rewriteBatchedStatements=true
  driverClassName: com.mysql.cj.jdbc.Driver
  username: root
  password: root
#ds3:
#  type: com.zaxxer.hikari.HikariDataSource
#  jdbcUrl: jdbc:mysql://127.0.0.1:3306/employees?rewriteBatchedStatements=true
#  driverClassName: com.mysql.cj.jdbc.Driver
#  username: root
#  password: root
#

## 多数据源
#dynamic:
#  type: com.zaxxer.hikari.HikariDataSource
#  strict: true #严格模式（指定的源不存时：严格模式会抛异常；非严格模式用默认源）
#  default: db_user_1 #指定默认数据源
#  db_user_1:
#    schema: db_user
#    jdbcUrl: jdbc:mysql://localhost:3306/db_user?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
#  db_user_2:
#    schema: db_user
#    jdbcUrl: jdbc:mysql://localhost:3307/db_user?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456

drink:
  main:
    database: MySQL
    datasource: normalDs1
  sub:
    database: SqlServer
    datasource: normalDs2
#  readonly:
#    database: H2
#    datasource: normalDs3
#  dynamic:
#    database: H2
#    datasource: dynamicDs