spring:
  output:
    ansi:
      enabled: always
  profiles:
    active: dev
  # 最低程度配置下只需要提供一个数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/employees?rewriteBatchedStatements=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
#    dynamic:
#      enabled: true
#      strict: true
#      datasource's:
#        d1:
#          type: com.zaxxer.hikari.HikariDataSource
#          url: jdbc:mysql://127.0.0.1:3306/employees?rewriteBatchedStatements=true
#          username: root
#          password: root
#          driverClassName: com.mysql.cj.jdbc.Driver
#        d2:
#          type: com.zaxxer.hikari.HikariDataSource
#          url: jdbc:mysql://127.0.0.1:3306/employees?rewriteBatchedStatements=true
#          username: root
#          password: root
#          driverClassName: com.mysql.cj.jdbc.Driver

server:
  port: 8080

# 不配置的情况下默认以database: mysql和print-sql: true模式运行
drink:
  database: mysql
  print-sql: true


